name: Gather info
on:
  workflow_dispatch
jobs:
  test:
    name: gather
    runs-on: ubuntu-20.04
    steps:
      - name: gather deps
        run: sudo apt-get update && sudo apt-get install -y iputils-ping tcpdump tcptraceroute
      - name: view iptables
        run: sudo iptables -S
      - name: view docker iptables
        run: docker build -t infrastructure-agent-builder -f ./build/Dockerfile . && docker run -t infrastructure-agent-builder /bin/bash -- iptables -S
        #- name: ping
        #  run: sudo -b tcpdump -i any -w dump && sleep 1 && tcptraceroute uploads.github.com
        #- name: dump
        #  run: cat dump | sudo tcpdump -n -nn -r -
